### ISSUE TITLE
garbage data when you turn a table pointer into a slice

### ISSUE THREAD

**Issue by nowakf** [driveyard/driveyard#1]
minimal reproduction:
```rust 
use soak::{RawTable, Columns};
use dioptre::{Fields, Field};

struct Foo<T: Columns, A>(RawTable<T>, Field<T, A>);

impl<T: Columns, A> Into<&'static [A]> for Foo<T, A> {
    fn into(mut self) -> &'static [A] {
        unsafe {std::slice::from_raw_parts(self.0.ptr(self.1), self.0.capacity()) }
    }
}
#[derive(Fields, Columns)]
struct Bar {
    field: u32,
}
fn main() {
    let cap = 10;
    let mut r = RawTable::<Bar>::with_capacity(cap);
    let slice : &[u32] = Foo(r, Bar::field).into();
    println!("{:?}", slice);
}
```
prints: [1663513591, 5, 1933537296, 22066, 0, 0, 0, 0, 0, 0]

Near as I can gather, the first 16 bytes are garbage independent of what type it is. Any idea what's going on here? Is it simply supposed to be garbage? Obviously, I haven't zeroed out the data there.

**Comment by nowakf** [comment]
Oh, just checked - it also happens if you write to the data:
```rust
    let ptr = r.ptr(Bar::field);
    for i in 0..r.capacity() {
        unsafe {
            let fref = &mut *ptr.add(i);
            *fref = i as u32;
        }
    }
```
resulted in 
[1443401396, 5, 2297118736, 21856, 4, 5, 6, 7, 8, 9]

**Comment by rpjohnst** [comment]
Sorry for the delay, I just learned GitHub doesn't automatically watch repos you create in organizations (or something)... 😰

The first version is expected. `RawTable` doesn't initialize anything for you- it's more like `RawVec` than `Vec`. In fact, creating a reference like that before initializing the buffer is undefined behavior, so *anything* could happen.

I can't reproduce the second version- when I paste that `for` loop immediately following the line `let mut r = RawTable::<Bar>::with_capacity(cap);`, I get `[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]` as output as expected. However, it is *also* undefined behavior, because you're creating a `&mut u32` before initializing it, so it's possible this is just a difference in compiler version.

The other big problem (and probably why you are seeing garbage in the second case) is that your moving `r` into a temporary `Foo` and then producing a `'static` reference from it introduces a use-after-free- the `Foo` is dropped at the end of the statement, which drops the `RawTable`, which frees the buffer. This is also undefined behavior.

The correct way to write this looks something like this:

```rust
use core::{ptr, slice};
use dioptre::Fields;
use soak::{RawTable, Columns};

#[derive(Fields, Columns)]
struct Bar { field: u32 }

fn main() {
    let mut table = RawTable::<Bar>::with_capacity(10);

    // initialize the buffer before creating any references:
    let fields = table.ptr(Bar::field);
    for i in 0..table.capacity() {
        unsafe { ptr::write(fields.add(i), i as u32); }
    }

    // only now is this sound:
    let slice: &[u32] = unsafe { slice::from_raw_parts(fields, table.capacity()) };
    println!("{:?}", slice);
}
```
