### ISSUE TITLE
Project goals

### ISSUE THREAD

**Issue by pickfire** [driveyard/driveyard#3]
What is the goal of the project and what features it aims to provide? Does it aim to be something like apache arrow or pandas? Or does it aim to provide something for game development?

I wonder can we do something like using bool on a bit level rather than using vec, like a customized column? And can we do comparison between fields like column a & column b? And can we temporary borrow a column which is useful for groupby?

**Comment by rpjohnst** [comment]
Sorry for the delay, I just learned GitHub doesn't automatically watch repos you create in organizations (or something)... 😰

I tried to cover this in the README:

> Driveyard attempts to stay minimal, while providing useful implementations of unsafe "glue" code. The interfaces it exposes are often still unsafe, but with less burden on callers.

So, much lower level than Apache Arrow or Pandas, and even lower level than things like "customized columns" or "temporary borrows." Instead, the goal is to package up tedious and error-prone low-level glue, so that those kinds of things can be built on top of it with a smaller `unsafe` proof obligation. Think "mechanism, not policy."

(Though of course if driveyard can provide a safe API, making that smaller obligation "nothing," that's great too. I just haven't done that for anything yet because it would introduce too much policy.)
